### PR TITLE
2016 is coming

### PR DESCRIPTION
**Pull request by pdebuyl**
add EuroSciPy 2016 dates
add past SciPy and EuroSciPy for 2015

### CODE REVIEW

**Comment by dpinte** [comment]
@rgommers Can you merge?

**Comment by dpinte** [comment]
ideally we would merge this with #18

**Comment by rgommers** [comment]
Merged. This PR looks fine, but seems not yet or only partially pushed. ``EuroScipy 2016`` on http://conference.scipy.org/ is not a link right now, and 2015 isn't yet present on http://conference.scipy.org/past.html

**Comment by rgommers** [comment]
> ideally we would merge this with #18

looked at gh-18, but that has a merge conflict right now.

**Comment by dpinte** [comment]
@rgommers yes, I'll have to merge the two and publish this one

**Pull request merged**
