### PR TITLE
2022 update

### PR DESCRIPTION
**Pull request by dpinte**
- add upcoming scipy
- update past.md
- update proceedings and `proc_link.js`

### CODE REVIEW

**Review by CholtonATX — APPROVED** [review]
LGTM

**Review by stefanv — APPROVED** [review]

**Comment by ltalirz** [comment]
Please merge :-) 

Google still leads some folks to conference.scipy.org where they don't find the 2022 edition

**Comment by stefanv** [comment]
I can merge, but someone needs to run the rsync, I presume.

**Comment by dpinte** [comment]
@stefanv I've sync'ed the site. It is up to date.

**Comment by ltalirz** [comment]
For me (Switzerland), https://conference.scipy.org/ currently can't be reached.
Does anyone else have the same problem?

By the way, scanning through the readme it seems the deployment on rackspace is currently a manual process (?). Any interest in automating this, e.g. via Github pages?

**Comment by dpinte** [comment]
@ltalirz Thanks for the report. It sounds like we lost the server that Rackspace offered us for some years. Issue tracked here #35

**Pull request merged**
