### PR TITLE
Github Action to automatically publish PRs to GitHub Pages

### PR DESCRIPTION
**Pull request by achabotl**
This is a follow-up to #51 with fixes:

- Fix `make` target to install dependencies
- Enable the workflow to write to the repo, which we need to write to the `gh-pages` branch.
- Force-push the `gh-pages` branch because we're overwriting the content every time.
- Specify the CNAME so we can redirect from conference.scipy.org.  Github automatically adds a CNAME file if you're publishing from a branch. But since the action wipes the `gh-pages` branch every time, the CNAME file goes away. ghp-import has the option to recreate it every time.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]

**Review by matthewfeickert — COMMENTED** [review]
@achabotl I'm a bit confused as to why you need to use `ghp-import` and manually do this work instead of just using GitHub Actions to do this (under https://github.com/scipy-conference/conference.scipy.org/settings/pages)

image

(I tend to do this in a 2 step process of [building the website and uplaoding the artifacts](https://github.com/scikit-hep/pyhf/blob/975ee43b71b2aa20664d47de47b5ddb79fc891b9/.github/workflows/docs.yml#L87-L96) and then in a deploy step actually doing the deployment) using [`actions/configure-pages`](https://github.com/actions/configure-pages) and [`actions/deploy-pages`](https://github.com/actions/deploy-pages).)

As you're just overwriting the history on the `gh-pages` branch

https://github.com/scipy-conference/conference.scipy.org/blob/5c2b29942d292811fb4fc17a285ef9cbd1bc2036/.github/workflows/publish.yml#L51

is there a reason to use a branch at all?

**Comment by matthewfeickert** [comment]
To be (hopefully) more helpful than just asking questions I opened up PR https://github.com/scipy-conference/conference.scipy.org/pull/53 targetting this PR's branch that impliments the changes I'm suggesting.

**Comment by achabotl** [comment]
Thanks @matthewfeickert. I used the `gh-pages` for the same reason you're using the actions: habit! :D 

Also, again, I'm weary of the Beta tag on on using Github Actions. That said, I'll merge PR #53 into this one and go for actions.

**Comment by achabotl** [comment]
And it works! Well, @matthewfeickert, now you've set a precedent, and I'll copy and paste this workflow file into all my future projects for the next decade. ;)

**Comment by matthewfeickert** [comment]
> Also, again, I'm weary of the Beta tag on on using Github Actions.

I think the "beta" here is relatively benign, as I've been using this across multiple orgs for more than a year with no issues. I've always found it to more mean "there might be API changes in the future" given the docs (https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) but it is at least a supported service from GitHub.

> Config updated.

@achabotl I see that the custom domain isn't set. Is this being handled a different way so that https://scipy-conference.github.io/conference.scipy.org/ properly redirects to https://conference.scipy.org/?

Can you also check the "Enforce HTTPS" button?

**Comment by achabotl** [comment]
I'm working with Jim and Numfocus to setup the DNS first. If I setup the custom domain, https://scipy-conference.github.io/conference.scipy.org/ is inaccessible and I can't see whether or not it works.

I'll enable HTTPS once the DNS is set up.

**Pull request merged**
