### PR TITLE
Enh/add proceedings for 2016

### PR DESCRIPTION
**Pull request by dpinte**
Proceedings have been uploaded to the server. This PR adds a link on this page http://conference.scipy.org/proceedings/. It is already live.

### CODE REVIEW

**Comment by dpinte** [comment]
@aterrel @rgommers anyone for a review?

**Comment by aterrel** [comment]
looks correct for the conference page. 

Looking at the proceedings page, need to update the navigation sidebar. Also the logo has a broken link.

**Comment by dpinte** [comment]
@aterrel thanks for checking, I've just uploaded the archive I received. I'll check what is going on with the broken links.

**Comment by aterrel** [comment]
looks like the `logo.png` file is missing from the proceedings static directory. which points to http://conference.scipy.org/proceedings/scipy2016/logo.png (see https://github.com/scipy-conference/scipy_proceedings/blob/2016/publisher/_templates/header.html.tmpl#L26 )

In the past the logo was both the logo and wordmark but this year it looks like the wordmark was separated: http://conference.scipy.org/proceedings/scipy2015/logo.png

The least fuss would be to copy a logo.png into the `proceedings/scipy2016`, e.g. https://docs.scipy.org/doc/scipy-0.9.0/reference/_static/scipyshiny_small.png

**Comment by dpinte** [comment]
the logo is in. I'll fix the side bar template asap

**Comment by aterrel** [comment]
looks like the 2015 logo was copied and it overrode the 2016 wordmark... Yeah should probably go fix the scipy-proceedings project to fix that...

**Comment by dpinte** [comment]
@aterrel I think we're good to go. I took one of the logo's from the website for the banner. I've also updated the javascript code used for the proceedings left menu. That code is not under version control which sounds wrong.

**Comment by aterrel** [comment]
Can you check it in. That's probably not even the most scary thing about
the site. For example the older conferences aren't archived anywhere and
require some pretty old software to run ( old versions of turbo gears ).

I started this repo for that purpose, but apparently never finished.
https://github.com/scipy-conference/conference-box

I don't have access to any of the machines anymore to help organize.

**Comment by dpinte** [comment]
@aterrel js files added to this PR! `make rsync` now properly updates them on the server

**Comment by aterrel** [comment]
👍

**Comment by stefanv** [comment]
Instead of trying to maintain TurboGears etc. going forward, how about
creating a Docker image that exposes a web server?

**Comment by dpinte** [comment]
Merging for now. @stefanv we should probably continue this discussion either on a ticket or live ;-)

**Pull request merged**
