### PR TITLE
Adds link for SciPy 2016.

### PR DESCRIPTION
**Pull request by cbrown-enthought**

### CODE REVIEW

**Comment by dpinte** [comment]
@rgommers Can we assign it to you?

**Comment by rgommers** [comment]
If assign means "press the green button", sure. But I'm not a SciPy conference organizer, nor do I admin the site. So I can't actually push these changes to the actual site.

**Comment by rgommers** [comment]
@dpinte I'll add you to a team that gives rights to this repo, that'll be easier

**Comment by dpinte** [comment]
@rgommers thanks! 

@cbrown-enthought Can you publish the updated site?

**Comment by cbrown-enthought** [comment]
Done and done.  Thanks, guys.

**Pull request merged**
