### PR TITLE
Change proceedings menu item to link to new proceedings site.

### PR DESCRIPTION
**Pull request by cbcunc**

### CODE REVIEW

**Comment by stefanv** [comment]
The new site looks great! It may be helpful to have the old proceedings more discoverable; right now, they're only linked in the footer.

**Comment by cbcunc** [comment]
> The new site looks great! It may be helpful to have the old proceedings more discoverable; right now, they're only linked in the footer.

@stefanv As soon as you click on the current year's listing, all the past years are right there in the left hand nav: https://proceedings.scipy.org/2024 . The link in the footer is for the past *conferences*, not the past proceedings. This PR is simply to fix the proceedings menu items on conference.scipy.org.

**Comment by rowanc1** [comment]
We have gone back all the way to 2008:

https://proceedings.scipy.org/2008

We also added DOIs for those years as well!

**Comment by stefanv** [comment]
@rowanc1 Yes, exactly, just a way to directly navigate from the front page to proceedings other than the latest.
Clicking on 2024 to find 2014 papers isn't something I'd have considered to do.
Anyway, sorry @cbcunc, you're right that this is not related to this PR!

**Comment by rowanc1** [comment]
Opened up an issue for that, want to do a better job of highlighting the proceedings of previous years for sure! Also organizing by author / package in the future would be awesome.

**Review by rowanc1 — APPROVED** [review]

**Comment by achabotl** [comment]
Thanks Rowan!

**Pull request merged**
