### PR TITLE
update info for EuroSciPy 2015

### PR DESCRIPTION
**Pull request by pdebuyl**

### CODE REVIEW

**Comment by rgommers** [comment]
@kjordahl @codersquid @aterrel this announcement is still not up on the site. Can one of you please push an update, or tell us how to get this done?

**Comment by codersquid** [comment]
I can merge, but I'm not sure how to push the update.

**Comment by rgommers** [comment]
@kjordahl @aterrel any idea who has admin access to conference.scipy.org?

**Comment by aterrel** [comment]
Looks like I have access to the box still. These are the folks on it:

aparker  aterrel  didrek  jim  mrterry  scipy  sheila

@rgommers 

Send me your key and I can add you as well.

**Comment by rgommers** [comment]
Rather add @dpinte or another Enthought person. Didrik, can you send Andy your ssh key and username?

**Comment by dpinte** [comment]
@rgommers sure, thanks!

**Comment by dpinte** [comment]
Looking at it, I have access to the box, the question is more about deploying the changes.

**Comment by dpinte** [comment]
@rgommers @aterrel it sounds like the missing bit is the `.pem` file to be able to publish the pelican files through ssh. Having admin access to the box might also help but it is probably better to keep using the official publication workflow.

**Comment by pdebuyl** [comment]
As long as you have ssh access, all that matters is that the user you login as has write permission to `/srv/www/conference/output` on the server. The pem file plays no role in the process apart from granting access.

**Comment by dpinte** [comment]
And the problem is having write permission ;-) So we need the pem file...

**Comment by dpinte** [comment]
Site updated. Workflow is not really good. Will try to get things in a better shape and post updated instructions.

**Comment by pdebuyl** [comment]
Thanks Didrik!

Is there something else, apart from the server issues (auth and permissions) that you would like to improve?

**Pull request merged**
